version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - chat-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: chatuser
      RABBITMQ_DEFAULT_PASS: chatpass123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - chat-network
    restart: unless-stopped

volumes:
  redis_data:
  rabbitmq_data:

networks:
  chat-network:
    driver: bridge 